#!/bin/sh

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E '(.js)$')

if [[ "$STAGED_FILES" = "" ]]; then
  exit 0
fi

PASS=true

echo -e "\nValidating Javascript:\n"

# Check for standard
which node_modules/.bin/standard &> /dev/null
if [[ "$?" == 1 ]]; then
  echo -e "\t\033[41mPlease install Standard\033[0m"
  exit 1
fi

for FILE in $STAGED_FILES
do
  node_modules/.bin/standard --fix "$FILE" > /dev/null
  git add "$FILE"
  node_modules/.bin/standard "$FILE" --verbose | node_modules/.bin/snazzy


  if [[ "$?" == 0 ]]; then
    echo -e "\t\033[32mStandard Passed: $FILE\033[0m"
  else
    echo -e "\t\033[41mStandard Failed: $FILE\033[0m"
    PASS=false
  fi
done

echo -e "\nJavascript validation completed!\n"

if ! $PASS; then
  echo -e "\033[41mCOMMIT FAILED:\033[0m Your commit contains files that should pass Standard but do not. Please fix the Standard errors and try again.\n"
  exit 1
else
  echo -e "\033[42mCOMMIT SUCCEEDED\033[0m\n"
fi

exit $?
