module.exports = function (app) {
  app.post('/typeahead/name/:typeaheadkey/search/:userinput', function (req, res) {
    setTimeout(() => {
      res.json({
        "startsWith": [{
          "cfd_companyname": "EGC Critical Components",
          "cfd_companylocation": "",
          "cfd_cmpyaccountmanager": "Charlie Spaneas",
          "companyid": "00566B5ABFE4264EBF2ED46E2043040E",
          "cfd_companymeta_type": "C",
          "cfd_cmpyacctmgrunid": "F2E2654A6635989EDA6F366391E73FD4",
          "cfd_companyaddress": "8103 Rankin Rd",
          "cfd_companycity": "Humble",
          "cfd_companystate": "TX",
          "cfd_companypostalcode": "",
          "cfd_companycountry": "USA",
          "cfd_companybusinesscategories": "Tier 1",
          "cfd_companyphonenumber": "2817746100",
          "cfd_companyfaxnumber": "",
          "cfd_companyaddress2": "",
          "cfd_companyaddress3": "",
          "cfd_companypostalcodeplus4": "",
          "cfd_companycounty": "",
          "cfd_companymarketingcategories": "Lead",
          "partnerid": "                                ",
          "cfd_companyregion": "",
          "cfd_companyindustrycategory": "Manufacturing",
          "cfd_companycustomernumber": "",
          "cfd_customernumber": "",
          "cfd_businesscategories": "Tier 1",
          "cfd_suppliername": "EGC Critical Components",
          "supplierid": "00566B5ABFE4264EBF2ED46E2043040E",
          "label": "EGC Critical Components::::C",
          "value": "EGC Critical Components"
        }, {
          "cfd_companyname": "Elevate",
          "cfd_companylocation": "",
          "cfd_cmpyaccountmanager": "Jacy Robb",
          "companyid": "00724C12F8F6B0C547FF8401CDA35B70",
          "cfd_companymeta_type": "P",
          "cfd_cmpyacctmgrunid": "F787E0FD682B920D5344FBF062092902",
          "cfd_companyaddress": "4150 International Plaza",
          "cfd_companycity": "Ft Worth",
          "cfd_companystate": "TX",
          "cfd_companypostalcode": "76109",
          "cfd_companycountry": "",
          "cfd_companybusinesscategories": "Tier 1",
          "cfd_companyphonenumber": "8179281500",
          "cfd_companyfaxnumber": "",
          "cfd_companyaddress2": "Suite 300",
          "cfd_companyaddress3": "",
          "cfd_companypostalcodeplus4": "",
          "cfd_companycounty": "",
          "cfd_companymarketingcategories": "Lead",
          "partnerid": "                                ",
          "cfd_companyregion": "",
          "cfd_companyindustrycategory": "Services",
          "cfd_companycustomernumber": "",
          "cfd_customernumber": "",
          "cfd_businesscategories": "Tier 1",
          "cfd_suppliername": "Elevate",
          "supplierid": "00724C12F8F6B0C547FF8401CDA35B70",
          "label": "Elevate::::P",
          "value": "Elevate"
        }, {
          "cfd_companyname": "Esurance Insurance Services, Inc.",
          "cfd_companylocation": "",
          "cfd_cmpyaccountmanager": "Charlie Spaneas",
          "companyid": "007C2440B7AD4B1B90EE31B53914E0E3",
          "cfd_companymeta_type": "P",
          "cfd_cmpyacctmgrunid": "F2E2654A6635989EDA6F366391E73FD4",
          "cfd_companyaddress": "650 Davis Street",
          "cfd_companycity": "San Francisco",
          "cfd_companystate": "CA",
          "cfd_companypostalcode": "",
          "cfd_companycountry": "",
          "cfd_companybusinesscategories": "",
          "cfd_companyphonenumber": "4158754559",
          "cfd_companyfaxnumber": "",
          "cfd_companyaddress2": "",
          "cfd_companyaddress3": "",
          "cfd_companypostalcodeplus4": "",
          "cfd_companycounty": "",
          "cfd_companymarketingcategories": "Lead",
          "partnerid": "                                ",
          "cfd_companyregion": "",
          "cfd_companyindustrycategory": "Insurance",
          "cfd_companycustomernumber": "",
          "cfd_customernumber": "",
          "cfd_businesscategories": "",
          "cfd_suppliername": "Esurance Insurance Services, Inc.",
          "supplierid": "007C2440B7AD4B1B90EE31B53914E0E3",
          "label": "Esurance Insurance Services, Inc.::::P",
          "value": "Esurance Insurance Services, Inc."
        }, {
          "cfd_companyname": "eG Innovations",
          "cfd_companylocation": "",
          "cfd_cmpyaccountmanager": "Charlie Spaneas",
          "companyid": "00922EE44E42616E6AD0078A15C92284",
          "cfd_companymeta_type": "P",
          "cfd_cmpyacctmgrunid": "F2E2654A6635989EDA6F366391E73FD4",
          "cfd_companyaddress": "33 Wood Avenue South",
          "cfd_companycity": "Iselin",
          "cfd_companystate": "NJ",
          "cfd_companypostalcode": "",
          "cfd_companycountry": "USA",
          "cfd_companybusinesscategories": "Tier 1",
          "cfd_companyphonenumber": "8665266700",
          "cfd_companyfaxnumber": "",
          "cfd_companyaddress2": "",
          "cfd_companyaddress3": "",
          "cfd_companypostalcodeplus4": "",
          "cfd_companycounty": "",
          "cfd_companymarketingcategories": "Lead",
          "partnerid": "                                ",
          "cfd_companyregion": "",
          "cfd_companyindustrycategory": "Software",
          "cfd_companycustomernumber": "",
          "cfd_customernumber": "",
          "cfd_businesscategories": "Tier 1",
          "cfd_suppliername": "eG Innovations",
          "supplierid": "00922EE44E42616E6AD0078A15C92284",
          "label": "eG Innovations::::P",
          "value": "eG Innovations"
        }, {
          "cfd_companyname": "Edgemate, Inc.",
          "cfd_companylocation": "",
          "cfd_cmpyaccountmanager": "Charlie Spaneas",
          "companyid": "00CA6C31E6F902AF64E47E6EA44644AE",
          "cfd_companymeta_type": "C",
          "cfd_cmpyacctmgrunid": "F2E2654A6635989EDA6F366391E73FD4",
          "cfd_companyaddress": "333 E Closson Rd",
          "cfd_companycity": "Roaring Spring",
          "cfd_companystate": "PA",
          "cfd_companypostalcode": "16673-2237",
          "cfd_companycountry": "United States",
          "cfd_companybusinesscategories": "Tier 1",
          "cfd_companyphonenumber": "(814) 224-5717",
          "cfd_companyfaxnumber": "",
          "cfd_companyaddress2": "",
          "cfd_companyaddress3": "",
          "cfd_companypostalcodeplus4": "",
          "cfd_companycounty": "",
          "cfd_companymarketingcategories": "Lead",
          "partnerid": "                                ",
          "cfd_companyregion": "",
          "cfd_companyindustrycategory": "Manufacturing",
          "cfd_companycustomernumber": "",
          "cfd_customernumber": "",
          "cfd_businesscategories": "Tier 1",
          "cfd_suppliername": "Edgemate, Inc.",
          "supplierid": "00CA6C31E6F902AF64E47E6EA44644AE",
          "label": "Edgemate, Inc.::::C",
          "value": "Edgemate, Inc."
        }, {
          "cfd_companyname": "Elliott Davis Decosimo, LLC",
          "cfd_companylocation": "",
          "cfd_cmpyaccountmanager": "Charlie Spaneas",
          "companyid": "00D1BAE7BCDA2A7A5D0DAD74A9675662",
          "cfd_companymeta_type": "C",
          "cfd_cmpyacctmgrunid": "F2E2654A6635989EDA6F366391E73FD4",
          "cfd_companyaddress": "200 E Broad St",
          "cfd_companycity": "Greenville",
          "cfd_companystate": "SC",
          "cfd_companypostalcode": "29601-2887",
          "cfd_companycountry": "United States",
          "cfd_companybusinesscategories": "Tier 1",
          "cfd_companyphonenumber": "(864) 242-2698",
          "cfd_companyfaxnumber": "",
          "cfd_companyaddress2": "",
          "cfd_companyaddress3": "",
          "cfd_companypostalcodeplus4": "",
          "cfd_companycounty": "",
          "cfd_companymarketingcategories": "Lead",
          "partnerid": "                                ",
          "cfd_companyregion": "",
          "cfd_companyindustrycategory": "business services",
          "cfd_companycustomernumber": "",
          "cfd_customernumber": "",
          "cfd_businesscategories": "Tier 1",
          "cfd_suppliername": "Elliott Davis Decosimo, LLC",
          "supplierid": "00D1BAE7BCDA2A7A5D0DAD74A9675662",
          "label": "Elliott Davis Decosimo, LLC::::C",
          "value": "Elliott Davis Decosimo, LLC"
        }, {
          "cfd_companyname": "ED-COM Software Inc.",
          "cfd_companylocation": "",
          "cfd_cmpyaccountmanager": "Charlie Spaneas",
          "companyid": "00E7691B98887951BB9DBAA4F3419CE3",
          "cfd_companymeta_type": "P",
          "cfd_cmpyacctmgrunid": "F2E2654A6635989EDA6F366391E73FD4",
          "cfd_companyaddress": "1853 Russell Rd",
          "cfd_companycity": "Ottawa",
          "cfd_companystate": "ON",
          "cfd_companypostalcode": "",
          "cfd_companycountry": "Canada",
          "cfd_companybusinesscategories": "Tier 1",
          "cfd_companyphonenumber": "6134823386",
          "cfd_companyfaxnumber": "",
          "cfd_companyaddress2": "",
          "cfd_companyaddress3": "",
          "cfd_companypostalcodeplus4": "",
          "cfd_companycounty": "",
          "cfd_companymarketingcategories": "Lead",
          "partnerid": "                                ",
          "cfd_companyregion": "",
          "cfd_companyindustrycategory": "",
          "cfd_companycustomernumber": "",
          "cfd_customernumber": "",
          "cfd_businesscategories": "Tier 1",
          "cfd_suppliername": "ED-COM Software Inc.",
          "supplierid": "00E7691B98887951BB9DBAA4F3419CE3",
          "label": "ED-COM Software Inc.::::P",
          "value": "ED-COM Software Inc."
        }, {
          "cfd_companyname": "Energy Transfer Equity",
          "cfd_companylocation": "",
          "cfd_cmpyaccountmanager": "Jacy Robb",
          "companyid": "00FD75AC4E4B6066DA6ECB619502A277",
          "cfd_companymeta_type": "P",
          "cfd_cmpyacctmgrunid": "F787E0FD682B920D5344FBF062092902",
          "cfd_companyaddress": "",
          "cfd_companycity": "Dallas",
          "cfd_companystate": "TX",
          "cfd_companypostalcode": "",
          "cfd_companycountry": "",
          "cfd_companybusinesscategories": "Tier 1",
          "cfd_companyphonenumber": "",
          "cfd_companyfaxnumber": "",
          "cfd_companyaddress2": "",
          "cfd_companyaddress3": "",
          "cfd_companypostalcodeplus4": "",
          "cfd_companycounty": "",
          "cfd_companymarketingcategories": "Lead",
          "partnerid": "                                ",
          "cfd_companyregion": "",
          "cfd_companyindustrycategory": "Financial",
          "cfd_companycustomernumber": "",
          "cfd_customernumber": "",
          "cfd_businesscategories": "Tier 1",
          "cfd_suppliername": "Energy Transfer Equity",
          "supplierid": "00FD75AC4E4B6066DA6ECB619502A277",
          "label": "Energy Transfer Equity::::P",
          "value": "Energy Transfer Equity"
        }, {
          "cfd_companyname": "Express Scripts, Inc.",
          "cfd_companylocation": "",
          "cfd_cmpyaccountmanager": "Charlie Spaneas",
          "companyid": "00FFD87735D6944C115C129AA2EC4CEA",
          "cfd_companymeta_type": "C",
          "cfd_cmpyacctmgrunid": "F2E2654A6635989EDA6F366391E73FD4",
          "cfd_companyaddress": "1 Express Way Stop 2w02",
          "cfd_companycity": "Saint Louis",
          "cfd_companystate": "MO",
          "cfd_companypostalcode": "63121-1824",
          "cfd_companycountry": "United States",
          "cfd_companybusinesscategories": "Tier 1",
          "cfd_companyphonenumber": "(314) 996-0900",
          "cfd_companyfaxnumber": "",
          "cfd_companyaddress2": "",
          "cfd_companyaddress3": "",
          "cfd_companypostalcodeplus4": "",
          "cfd_companycounty": "",
          "cfd_companymarketingcategories": "Lead",
          "partnerid": "                                ",
          "cfd_companyregion": "",
          "cfd_companyindustrycategory": "Retail",
          "cfd_companycustomernumber": "",
          "cfd_customernumber": "",
          "cfd_businesscategories": "Tier 1",
          "cfd_suppliername": "Express Scripts, Inc.",
          "supplierid": "00FFD87735D6944C115C129AA2EC4CEA",
          "label": "Express Scripts, Inc.::::C",
          "value": "Express Scripts, Inc."
        }, {
          "cfd_companyname": "East Penn Manufacturing",
          "cfd_companylocation": "",
          "cfd_cmpyaccountmanager": "Charlie Spaneas",
          "companyid": "01011604C97BB660D12F17069AF4FFDE",
          "cfd_companymeta_type": "P",
          "cfd_cmpyacctmgrunid": "F2E2654A6635989EDA6F366391E73FD4",
          "cfd_companyaddress": "1 Deka Road",
          "cfd_companycity": "Lyon Station",
          "cfd_companystate": "PA",
          "cfd_companypostalcode": "",
          "cfd_companycountry": "",
          "cfd_companybusinesscategories": "",
          "cfd_companyphonenumber": "7202882490",
          "cfd_companyfaxnumber": "",
          "cfd_companyaddress2": "",
          "cfd_companyaddress3": "",
          "cfd_companypostalcodeplus4": "",
          "cfd_companycounty": "",
          "cfd_companymarketingcategories": "Lead",
          "partnerid": "                                ",
          "cfd_companyregion": "",
          "cfd_companyindustrycategory": "Manufacturing",
          "cfd_companycustomernumber": "",
          "cfd_customernumber": "",
          "cfd_businesscategories": "",
          "cfd_suppliername": "East Penn Manufacturing",
          "supplierid": "01011604C97BB660D12F17069AF4FFDE",
          "label": "East Penn Manufacturing::::P",
          "value": "East Penn Manufacturing"
        }],
        "contains": [{
          "cfd_companyname": "Hillerich \u0026 Bradsby Co.",
          "cfd_companylocation": "",
          "cfd_cmpyaccountmanager": "Charlie Spaneas",
          "companyid": "0002CD9707A38029B9BAEACB433EB336",
          "cfd_companymeta_type": "C",
          "cfd_cmpyacctmgrunid": "F2E2654A6635989EDA6F366391E73FD4",
          "cfd_companyaddress": "800 W Main St",
          "cfd_companycity": "Louisville",
          "cfd_companystate": "KY",
          "cfd_companypostalcode": "40202-2620",
          "cfd_companycountry": "United States",
          "cfd_companybusinesscategories": "Tier 1",
          "cfd_companyphonenumber": "(502) 585-5226",
          "cfd_companyfaxnumber": "",
          "cfd_companyaddress2": "",
          "cfd_companyaddress3": "",
          "cfd_companypostalcodeplus4": "",
          "cfd_companycounty": "",
          "cfd_companymarketingcategories": "Lead",
          "partnerid": "                                ",
          "cfd_companyregion": "",
          "cfd_companyindustrycategory": "Manufacturing",
          "cfd_companycustomernumber": "",
          "cfd_customernumber": "",
          "cfd_businesscategories": "Tier 1",
          "cfd_suppliername": "Hillerich \u0026 Bradsby Co.",
          "supplierid": "0002CD9707A38029B9BAEACB433EB336",
          "label": "Hillerich \u0026 Bradsby Co.::::C",
          "value": "Hillerich \u0026 Bradsby Co."
        }, {
          "cfd_companyname": "Aspen Institute",
          "cfd_companylocation": "",
          "cfd_cmpyaccountmanager": "Charlie Spaneas",
          "companyid": "0004404DFF0A0EB18178728A907C114F",
          "cfd_companymeta_type": "P",
          "cfd_cmpyacctmgrunid": "F2E2654A6635989EDA6F366391E73FD4",
          "cfd_companyaddress": "One Dupont Circle",
          "cfd_companycity": "Washington",
          "cfd_companystate": "DC",
          "cfd_companypostalcode": "",
          "cfd_companycountry": "",
          "cfd_companybusinesscategories": "",
          "cfd_companyphonenumber": "2027365843",
          "cfd_companyfaxnumber": "",
          "cfd_companyaddress2": "",
          "cfd_companyaddress3": "",
          "cfd_companypostalcodeplus4": "",
          "cfd_companycounty": "",
          "cfd_companymarketingcategories": "Lead",
          "partnerid": "                                ",
          "cfd_companyregion": "",
          "cfd_companyindustrycategory": "Services",
          "cfd_companycustomernumber": "",
          "cfd_customernumber": "",
          "cfd_businesscategories": "",
          "cfd_suppliername": "Aspen Institute",
          "supplierid": "0004404DFF0A0EB18178728A907C114F",
          "label": "Aspen Institute::::P",
          "value": "Aspen Institute"
        }, {
          "cfd_companyname": "Cerberus Capital Management, L.P.",
          "cfd_companylocation": "",
          "cfd_cmpyaccountmanager": "Charlie Spaneas",
          "companyid": "0007AC25F5F2EDF3D0F37618D2E043DB",
          "cfd_companymeta_type": "C",
          "cfd_cmpyacctmgrunid": "F2E2654A6635989EDA6F366391E73FD4",
          "cfd_companyaddress": "299 Park Ave 22nd Floor",
          "cfd_companycity": "New York",
          "cfd_companystate": "NY",
          "cfd_companypostalcode": "10171-0002",
          "cfd_companycountry": "United States",
          "cfd_companybusinesscategories": "Tier 1",
          "cfd_companyphonenumber": "(212) 891-2100",
          "cfd_companyfaxnumber": "",
          "cfd_companyaddress2": "",
          "cfd_companyaddress3": "",
          "cfd_companypostalcodeplus4": "",
          "cfd_companycounty": "",
          "cfd_companymarketingcategories": "Lead",
          "partnerid": "                                ",
          "cfd_companyregion": "",
          "cfd_companyindustrycategory": "Finance",
          "cfd_companycustomernumber": "",
          "cfd_customernumber": "",
          "cfd_businesscategories": "Tier 1",
          "cfd_suppliername": "Cerberus Capital Management, L.P.",
          "supplierid": "0007AC25F5F2EDF3D0F37618D2E043DB",
          "label": "Cerberus Capital Management, L.P.::::C",
          "value": "Cerberus Capital Management, L.P."
        }, {
          "cfd_companyname": "Citrus Valley Hospice",
          "cfd_companylocation": "",
          "cfd_cmpyaccountmanager": "Charlie Spaneas",
          "companyid": "0009A08068F1E5BA1B0E84A89AA6C90D",
          "cfd_companymeta_type": "C",
          "cfd_cmpyacctmgrunid": "F2E2654A6635989EDA6F366391E73FD4",
          "cfd_companyaddress": "820 N Phillips Ave",
          "cfd_companycity": "West Covina",
          "cfd_companystate": "CA",
          "cfd_companypostalcode": "91791-1121",
          "cfd_companycountry": "United States",
          "cfd_companybusinesscategories": "Tier 1",
          "cfd_companyphonenumber": "(626) 859-2263",
          "cfd_companyfaxnumber": "",
          "cfd_companyaddress2": "",
          "cfd_companyaddress3": "",
          "cfd_companypostalcodeplus4": "",
          "cfd_companycounty": "",
          "cfd_companymarketingcategories": "Lead",
          "partnerid": "                                ",
          "cfd_companyregion": "",
          "cfd_companyindustrycategory": "Healthcare",
          "cfd_companycustomernumber": "",
          "cfd_customernumber": "",
          "cfd_businesscategories": "Tier 1",
          "cfd_suppliername": "Citrus Valley Hospice",
          "supplierid": "0009A08068F1E5BA1B0E84A89AA6C90D",
          "label": "Citrus Valley Hospice::::C",
          "value": "Citrus Valley Hospice"
        }, {
          "cfd_companyname": "Medeanalytics, Inc.",
          "cfd_companylocation": "",
          "cfd_cmpyaccountmanager": "Charlie Spaneas",
          "companyid": "000B1BCD7BFD8E0C3B95F8E4ADC50840",
          "cfd_companymeta_type": "C",
          "cfd_cmpyacctmgrunid": "F2E2654A6635989EDA6F366391E73FD4",
          "cfd_companyaddress": "5858 Horton St",
          "cfd_companycity": "Emeryville",
          "cfd_companystate": "CA",
          "cfd_companypostalcode": "94608-2006",
          "cfd_companycountry": "United States",
          "cfd_companybusinesscategories": "Tier 1",
          "cfd_companyphonenumber": "(510) 379-3300 668",
          "cfd_companyfaxnumber": "",
          "cfd_companyaddress2": "",
          "cfd_companyaddress3": "",
          "cfd_companypostalcodeplus4": "",
          "cfd_companycounty": "",
          "cfd_companymarketingcategories": "Lead",
          "partnerid": "                                ",
          "cfd_companyregion": "",
          "cfd_companyindustrycategory": "Business Services",
          "cfd_companycustomernumber": "",
          "cfd_customernumber": "",
          "cfd_businesscategories": "Tier 1",
          "cfd_suppliername": "Medeanalytics, Inc.",
          "supplierid": "000B1BCD7BFD8E0C3B95F8E4ADC50840",
          "label": "Medeanalytics, Inc.::::C",
          "value": "Medeanalytics, Inc."
        }],
        "data": [{
          "cfd_companyname": "EGC Critical Components",
          "cfd_companylocation": "",
          "cfd_cmpyaccountmanager": "Charlie Spaneas",
          "companyid": "00566B5ABFE4264EBF2ED46E2043040E",
          "cfd_companymeta_type": "C",
          "cfd_cmpyacctmgrunid": "F2E2654A6635989EDA6F366391E73FD4",
          "cfd_companyaddress": "8103 Rankin Rd",
          "cfd_companycity": "Humble",
          "cfd_companystate": "TX",
          "cfd_companypostalcode": "",
          "cfd_companycountry": "USA",
          "cfd_companybusinesscategories": "Tier 1",
          "cfd_companyphonenumber": "2817746100",
          "cfd_companyfaxnumber": "",
          "cfd_companyaddress2": "",
          "cfd_companyaddress3": "",
          "cfd_companypostalcodeplus4": "",
          "cfd_companycounty": "",
          "cfd_companymarketingcategories": "Lead",
          "partnerid": "                                ",
          "cfd_companyregion": "",
          "cfd_companyindustrycategory": "Manufacturing",
          "cfd_companycustomernumber": "",
          "cfd_customernumber": "",
          "cfd_businesscategories": "Tier 1",
          "cfd_suppliername": "EGC Critical Components",
          "supplierid": "00566B5ABFE4264EBF2ED46E2043040E",
          "label": "EGC Critical Components::::C",
          "value": "EGC Critical Components"
        }, {
          "cfd_companyname": "Elevate",
          "cfd_companylocation": "",
          "cfd_cmpyaccountmanager": "Jacy Robb",
          "companyid": "00724C12F8F6B0C547FF8401CDA35B70",
          "cfd_companymeta_type": "P",
          "cfd_cmpyacctmgrunid": "F787E0FD682B920D5344FBF062092902",
          "cfd_companyaddress": "4150 International Plaza",
          "cfd_companycity": "Ft Worth",
          "cfd_companystate": "TX",
          "cfd_companypostalcode": "76109",
          "cfd_companycountry": "",
          "cfd_companybusinesscategories": "Tier 1",
          "cfd_companyphonenumber": "8179281500",
          "cfd_companyfaxnumber": "",
          "cfd_companyaddress2": "Suite 300",
          "cfd_companyaddress3": "",
          "cfd_companypostalcodeplus4": "",
          "cfd_companycounty": "",
          "cfd_companymarketingcategories": "Lead",
          "partnerid": "                                ",
          "cfd_companyregion": "",
          "cfd_companyindustrycategory": "Services",
          "cfd_companycustomernumber": "",
          "cfd_customernumber": "",
          "cfd_businesscategories": "Tier 1",
          "cfd_suppliername": "Elevate",
          "supplierid": "00724C12F8F6B0C547FF8401CDA35B70",
          "label": "Elevate::::P",
          "value": "Elevate"
        }, {
          "cfd_companyname": "Esurance Insurance Services, Inc.",
          "cfd_companylocation": "",
          "cfd_cmpyaccountmanager": "Charlie Spaneas",
          "companyid": "007C2440B7AD4B1B90EE31B53914E0E3",
          "cfd_companymeta_type": "P",
          "cfd_cmpyacctmgrunid": "F2E2654A6635989EDA6F366391E73FD4",
          "cfd_companyaddress": "650 Davis Street",
          "cfd_companycity": "San Francisco",
          "cfd_companystate": "CA",
          "cfd_companypostalcode": "",
          "cfd_companycountry": "",
          "cfd_companybusinesscategories": "",
          "cfd_companyphonenumber": "4158754559",
          "cfd_companyfaxnumber": "",
          "cfd_companyaddress2": "",
          "cfd_companyaddress3": "",
          "cfd_companypostalcodeplus4": "",
          "cfd_companycounty": "",
          "cfd_companymarketingcategories": "Lead",
          "partnerid": "                                ",
          "cfd_companyregion": "",
          "cfd_companyindustrycategory": "Insurance",
          "cfd_companycustomernumber": "",
          "cfd_customernumber": "",
          "cfd_businesscategories": "",
          "cfd_suppliername": "Esurance Insurance Services, Inc.",
          "supplierid": "007C2440B7AD4B1B90EE31B53914E0E3",
          "label": "Esurance Insurance Services, Inc.::::P",
          "value": "Esurance Insurance Services, Inc."
        }, {
          "cfd_companyname": "eG Innovations",
          "cfd_companylocation": "",
          "cfd_cmpyaccountmanager": "Charlie Spaneas",
          "companyid": "00922EE44E42616E6AD0078A15C92284",
          "cfd_companymeta_type": "P",
          "cfd_cmpyacctmgrunid": "F2E2654A6635989EDA6F366391E73FD4",
          "cfd_companyaddress": "33 Wood Avenue South",
          "cfd_companycity": "Iselin",
          "cfd_companystate": "NJ",
          "cfd_companypostalcode": "",
          "cfd_companycountry": "USA",
          "cfd_companybusinesscategories": "Tier 1",
          "cfd_companyphonenumber": "8665266700",
          "cfd_companyfaxnumber": "",
          "cfd_companyaddress2": "",
          "cfd_companyaddress3": "",
          "cfd_companypostalcodeplus4": "",
          "cfd_companycounty": "",
          "cfd_companymarketingcategories": "Lead",
          "partnerid": "                                ",
          "cfd_companyregion": "",
          "cfd_companyindustrycategory": "Software",
          "cfd_companycustomernumber": "",
          "cfd_customernumber": "",
          "cfd_businesscategories": "Tier 1",
          "cfd_suppliername": "eG Innovations",
          "supplierid": "00922EE44E42616E6AD0078A15C92284",
          "label": "eG Innovations::::P",
          "value": "eG Innovations"
        }, {
          "cfd_companyname": "Edgemate, Inc.",
          "cfd_companylocation": "",
          "cfd_cmpyaccountmanager": "Charlie Spaneas",
          "companyid": "00CA6C31E6F902AF64E47E6EA44644AE",
          "cfd_companymeta_type": "C",
          "cfd_cmpyacctmgrunid": "F2E2654A6635989EDA6F366391E73FD4",
          "cfd_companyaddress": "333 E Closson Rd",
          "cfd_companycity": "Roaring Spring",
          "cfd_companystate": "PA",
          "cfd_companypostalcode": "16673-2237",
          "cfd_companycountry": "United States",
          "cfd_companybusinesscategories": "Tier 1",
          "cfd_companyphonenumber": "(814) 224-5717",
          "cfd_companyfaxnumber": "",
          "cfd_companyaddress2": "",
          "cfd_companyaddress3": "",
          "cfd_companypostalcodeplus4": "",
          "cfd_companycounty": "",
          "cfd_companymarketingcategories": "Lead",
          "partnerid": "                                ",
          "cfd_companyregion": "",
          "cfd_companyindustrycategory": "Manufacturing",
          "cfd_companycustomernumber": "",
          "cfd_customernumber": "",
          "cfd_businesscategories": "Tier 1",
          "cfd_suppliername": "Edgemate, Inc.",
          "supplierid": "00CA6C31E6F902AF64E47E6EA44644AE",
          "label": "Edgemate, Inc.::::C",
          "value": "Edgemate, Inc."
        }, {
          "cfd_companyname": "Elliott Davis Decosimo, LLC",
          "cfd_companylocation": "",
          "cfd_cmpyaccountmanager": "Charlie Spaneas",
          "companyid": "00D1BAE7BCDA2A7A5D0DAD74A9675662",
          "cfd_companymeta_type": "C",
          "cfd_cmpyacctmgrunid": "F2E2654A6635989EDA6F366391E73FD4",
          "cfd_companyaddress": "200 E Broad St",
          "cfd_companycity": "Greenville",
          "cfd_companystate": "SC",
          "cfd_companypostalcode": "29601-2887",
          "cfd_companycountry": "United States",
          "cfd_companybusinesscategories": "Tier 1",
          "cfd_companyphonenumber": "(864) 242-2698",
          "cfd_companyfaxnumber": "",
          "cfd_companyaddress2": "",
          "cfd_companyaddress3": "",
          "cfd_companypostalcodeplus4": "",
          "cfd_companycounty": "",
          "cfd_companymarketingcategories": "Lead",
          "partnerid": "                                ",
          "cfd_companyregion": "",
          "cfd_companyindustrycategory": "business services",
          "cfd_companycustomernumber": "",
          "cfd_customernumber": "",
          "cfd_businesscategories": "Tier 1",
          "cfd_suppliername": "Elliott Davis Decosimo, LLC",
          "supplierid": "00D1BAE7BCDA2A7A5D0DAD74A9675662",
          "label": "Elliott Davis Decosimo, LLC::::C",
          "value": "Elliott Davis Decosimo, LLC"
        }, {
          "cfd_companyname": "ED-COM Software Inc.",
          "cfd_companylocation": "",
          "cfd_cmpyaccountmanager": "Charlie Spaneas",
          "companyid": "00E7691B98887951BB9DBAA4F3419CE3",
          "cfd_companymeta_type": "P",
          "cfd_cmpyacctmgrunid": "F2E2654A6635989EDA6F366391E73FD4",
          "cfd_companyaddress": "1853 Russell Rd",
          "cfd_companycity": "Ottawa",
          "cfd_companystate": "ON",
          "cfd_companypostalcode": "",
          "cfd_companycountry": "Canada",
          "cfd_companybusinesscategories": "Tier 1",
          "cfd_companyphonenumber": "6134823386",
          "cfd_companyfaxnumber": "",
          "cfd_companyaddress2": "",
          "cfd_companyaddress3": "",
          "cfd_companypostalcodeplus4": "",
          "cfd_companycounty": "",
          "cfd_companymarketingcategories": "Lead",
          "partnerid": "                                ",
          "cfd_companyregion": "",
          "cfd_companyindustrycategory": "",
          "cfd_companycustomernumber": "",
          "cfd_customernumber": "",
          "cfd_businesscategories": "Tier 1",
          "cfd_suppliername": "ED-COM Software Inc.",
          "supplierid": "00E7691B98887951BB9DBAA4F3419CE3",
          "label": "ED-COM Software Inc.::::P",
          "value": "ED-COM Software Inc."
        }, {
          "cfd_companyname": "Energy Transfer Equity",
          "cfd_companylocation": "",
          "cfd_cmpyaccountmanager": "Jacy Robb",
          "companyid": "00FD75AC4E4B6066DA6ECB619502A277",
          "cfd_companymeta_type": "P",
          "cfd_cmpyacctmgrunid": "F787E0FD682B920D5344FBF062092902",
          "cfd_companyaddress": "",
          "cfd_companycity": "Dallas",
          "cfd_companystate": "TX",
          "cfd_companypostalcode": "",
          "cfd_companycountry": "",
          "cfd_companybusinesscategories": "Tier 1",
          "cfd_companyphonenumber": "",
          "cfd_companyfaxnumber": "",
          "cfd_companyaddress2": "",
          "cfd_companyaddress3": "",
          "cfd_companypostalcodeplus4": "",
          "cfd_companycounty": "",
          "cfd_companymarketingcategories": "Lead",
          "partnerid": "                                ",
          "cfd_companyregion": "",
          "cfd_companyindustrycategory": "Financial",
          "cfd_companycustomernumber": "",
          "cfd_customernumber": "",
          "cfd_businesscategories": "Tier 1",
          "cfd_suppliername": "Energy Transfer Equity",
          "supplierid": "00FD75AC4E4B6066DA6ECB619502A277",
          "label": "Energy Transfer Equity::::P",
          "value": "Energy Transfer Equity"
        }, {
          "cfd_companyname": "Express Scripts, Inc.",
          "cfd_companylocation": "",
          "cfd_cmpyaccountmanager": "Charlie Spaneas",
          "companyid": "00FFD87735D6944C115C129AA2EC4CEA",
          "cfd_companymeta_type": "C",
          "cfd_cmpyacctmgrunid": "F2E2654A6635989EDA6F366391E73FD4",
          "cfd_companyaddress": "1 Express Way Stop 2w02",
          "cfd_companycity": "Saint Louis",
          "cfd_companystate": "MO",
          "cfd_companypostalcode": "63121-1824",
          "cfd_companycountry": "United States",
          "cfd_companybusinesscategories": "Tier 1",
          "cfd_companyphonenumber": "(314) 996-0900",
          "cfd_companyfaxnumber": "",
          "cfd_companyaddress2": "",
          "cfd_companyaddress3": "",
          "cfd_companypostalcodeplus4": "",
          "cfd_companycounty": "",
          "cfd_companymarketingcategories": "Lead",
          "partnerid": "                                ",
          "cfd_companyregion": "",
          "cfd_companyindustrycategory": "Retail",
          "cfd_companycustomernumber": "",
          "cfd_customernumber": "",
          "cfd_businesscategories": "Tier 1",
          "cfd_suppliername": "Express Scripts, Inc.",
          "supplierid": "00FFD87735D6944C115C129AA2EC4CEA",
          "label": "Express Scripts, Inc.::::C",
          "value": "Express Scripts, Inc."
        }, {
          "cfd_companyname": "East Penn Manufacturing",
          "cfd_companylocation": "",
          "cfd_cmpyaccountmanager": "Charlie Spaneas",
          "companyid": "01011604C97BB660D12F17069AF4FFDE",
          "cfd_companymeta_type": "P",
          "cfd_cmpyacctmgrunid": "F2E2654A6635989EDA6F366391E73FD4",
          "cfd_companyaddress": "1 Deka Road",
          "cfd_companycity": "Lyon Station",
          "cfd_companystate": "PA",
          "cfd_companypostalcode": "",
          "cfd_companycountry": "",
          "cfd_companybusinesscategories": "",
          "cfd_companyphonenumber": "7202882490",
          "cfd_companyfaxnumber": "",
          "cfd_companyaddress2": "",
          "cfd_companyaddress3": "",
          "cfd_companypostalcodeplus4": "",
          "cfd_companycounty": "",
          "cfd_companymarketingcategories": "Lead",
          "partnerid": "                                ",
          "cfd_companyregion": "",
          "cfd_companyindustrycategory": "Manufacturing",
          "cfd_companycustomernumber": "",
          "cfd_customernumber": "",
          "cfd_businesscategories": "",
          "cfd_suppliername": "East Penn Manufacturing",
          "supplierid": "01011604C97BB660D12F17069AF4FFDE",
          "label": "East Penn Manufacturing::::P",
          "value": "East Penn Manufacturing"
        }, {
          "cfd_companyname": "Hillerich \u0026 Bradsby Co.",
          "cfd_companylocation": "",
          "cfd_cmpyaccountmanager": "Charlie Spaneas",
          "companyid": "0002CD9707A38029B9BAEACB433EB336",
          "cfd_companymeta_type": "C",
          "cfd_cmpyacctmgrunid": "F2E2654A6635989EDA6F366391E73FD4",
          "cfd_companyaddress": "800 W Main St",
          "cfd_companycity": "Louisville",
          "cfd_companystate": "KY",
          "cfd_companypostalcode": "40202-2620",
          "cfd_companycountry": "United States",
          "cfd_companybusinesscategories": "Tier 1",
          "cfd_companyphonenumber": "(502) 585-5226",
          "cfd_companyfaxnumber": "",
          "cfd_companyaddress2": "",
          "cfd_companyaddress3": "",
          "cfd_companypostalcodeplus4": "",
          "cfd_companycounty": "",
          "cfd_companymarketingcategories": "Lead",
          "partnerid": "                                ",
          "cfd_companyregion": "",
          "cfd_companyindustrycategory": "Manufacturing",
          "cfd_companycustomernumber": "",
          "cfd_customernumber": "",
          "cfd_businesscategories": "Tier 1",
          "cfd_suppliername": "Hillerich \u0026 Bradsby Co.",
          "supplierid": "0002CD9707A38029B9BAEACB433EB336",
          "label": "Hillerich \u0026 Bradsby Co.::::C",
          "value": "Hillerich \u0026 Bradsby Co."
        }, {
          "cfd_companyname": "Aspen Institute",
          "cfd_companylocation": "",
          "cfd_cmpyaccountmanager": "Charlie Spaneas",
          "companyid": "0004404DFF0A0EB18178728A907C114F",
          "cfd_companymeta_type": "P",
          "cfd_cmpyacctmgrunid": "F2E2654A6635989EDA6F366391E73FD4",
          "cfd_companyaddress": "One Dupont Circle",
          "cfd_companycity": "Washington",
          "cfd_companystate": "DC",
          "cfd_companypostalcode": "",
          "cfd_companycountry": "",
          "cfd_companybusinesscategories": "",
          "cfd_companyphonenumber": "2027365843",
          "cfd_companyfaxnumber": "",
          "cfd_companyaddress2": "",
          "cfd_companyaddress3": "",
          "cfd_companypostalcodeplus4": "",
          "cfd_companycounty": "",
          "cfd_companymarketingcategories": "Lead",
          "partnerid": "                                ",
          "cfd_companyregion": "",
          "cfd_companyindustrycategory": "Services",
          "cfd_companycustomernumber": "",
          "cfd_customernumber": "",
          "cfd_businesscategories": "",
          "cfd_suppliername": "Aspen Institute",
          "supplierid": "0004404DFF0A0EB18178728A907C114F",
          "label": "Aspen Institute::::P",
          "value": "Aspen Institute"
        }, {
          "cfd_companyname": "Cerberus Capital Management, L.P.",
          "cfd_companylocation": "",
          "cfd_cmpyaccountmanager": "Charlie Spaneas",
          "companyid": "0007AC25F5F2EDF3D0F37618D2E043DB",
          "cfd_companymeta_type": "C",
          "cfd_cmpyacctmgrunid": "F2E2654A6635989EDA6F366391E73FD4",
          "cfd_companyaddress": "299 Park Ave 22nd Floor",
          "cfd_companycity": "New York",
          "cfd_companystate": "NY",
          "cfd_companypostalcode": "10171-0002",
          "cfd_companycountry": "United States",
          "cfd_companybusinesscategories": "Tier 1",
          "cfd_companyphonenumber": "(212) 891-2100",
          "cfd_companyfaxnumber": "",
          "cfd_companyaddress2": "",
          "cfd_companyaddress3": "",
          "cfd_companypostalcodeplus4": "",
          "cfd_companycounty": "",
          "cfd_companymarketingcategories": "Lead",
          "partnerid": "                                ",
          "cfd_companyregion": "",
          "cfd_companyindustrycategory": "Finance",
          "cfd_companycustomernumber": "",
          "cfd_customernumber": "",
          "cfd_businesscategories": "Tier 1",
          "cfd_suppliername": "Cerberus Capital Management, L.P.",
          "supplierid": "0007AC25F5F2EDF3D0F37618D2E043DB",
          "label": "Cerberus Capital Management, L.P.::::C",
          "value": "Cerberus Capital Management, L.P."
        }, {
          "cfd_companyname": "Citrus Valley Hospice",
          "cfd_companylocation": "",
          "cfd_cmpyaccountmanager": "Charlie Spaneas",
          "companyid": "0009A08068F1E5BA1B0E84A89AA6C90D",
          "cfd_companymeta_type": "C",
          "cfd_cmpyacctmgrunid": "F2E2654A6635989EDA6F366391E73FD4",
          "cfd_companyaddress": "820 N Phillips Ave",
          "cfd_companycity": "West Covina",
          "cfd_companystate": "CA",
          "cfd_companypostalcode": "91791-1121",
          "cfd_companycountry": "United States",
          "cfd_companybusinesscategories": "Tier 1",
          "cfd_companyphonenumber": "(626) 859-2263",
          "cfd_companyfaxnumber": "",
          "cfd_companyaddress2": "",
          "cfd_companyaddress3": "",
          "cfd_companypostalcodeplus4": "",
          "cfd_companycounty": "",
          "cfd_companymarketingcategories": "Lead",
          "partnerid": "                                ",
          "cfd_companyregion": "",
          "cfd_companyindustrycategory": "Healthcare",
          "cfd_companycustomernumber": "",
          "cfd_customernumber": "",
          "cfd_businesscategories": "Tier 1",
          "cfd_suppliername": "Citrus Valley Hospice",
          "supplierid": "0009A08068F1E5BA1B0E84A89AA6C90D",
          "label": "Citrus Valley Hospice::::C",
          "value": "Citrus Valley Hospice"
        }, {
          "cfd_companyname": "Medeanalytics, Inc.",
          "cfd_companylocation": "",
          "cfd_cmpyaccountmanager": "Charlie Spaneas",
          "companyid": "000B1BCD7BFD8E0C3B95F8E4ADC50840",
          "cfd_companymeta_type": "C",
          "cfd_cmpyacctmgrunid": "F2E2654A6635989EDA6F366391E73FD4",
          "cfd_companyaddress": "5858 Horton St",
          "cfd_companycity": "Emeryville",
          "cfd_companystate": "CA",
          "cfd_companypostalcode": "94608-2006",
          "cfd_companycountry": "United States",
          "cfd_companybusinesscategories": "Tier 1",
          "cfd_companyphonenumber": "(510) 379-3300 668",
          "cfd_companyfaxnumber": "",
          "cfd_companyaddress2": "",
          "cfd_companyaddress3": "",
          "cfd_companypostalcodeplus4": "",
          "cfd_companycounty": "",
          "cfd_companymarketingcategories": "Lead",
          "partnerid": "                                ",
          "cfd_companyregion": "",
          "cfd_companyindustrycategory": "Business Services",
          "cfd_companycustomernumber": "",
          "cfd_customernumber": "",
          "cfd_businesscategories": "Tier 1",
          "cfd_suppliername": "Medeanalytics, Inc.",
          "supplierid": "000B1BCD7BFD8E0C3B95F8E4ADC50840",
          "label": "Medeanalytics, Inc.::::C",
          "value": "Medeanalytics, Inc."
        }],
        "meta": {
          "queryRowCount": 35982
        }
      })
    }, 1000)
  })

  app.post('/typeahead/name/:typeaheadkey/search/', function (req, res) {
    setTimeout(() => {
      res.json({
        'data': [
          {
            'meta_universalid': '011C984330351D81008633C3A966D648',
            'companyname': 'test company 1',
            'ups_am_name': 'Jacy Robb',
            'label': 'test company 1::C',
            'value': '011C984330351D81008633C3A966D648'
          },
          {
            'meta_universalid': '0E29E0407341E301BEF0FBC34796C110',
            'companyname': 'API Company',
            'ups_am_name': 'Allen Swope',
            'label': 'API Company::C',
            'value': '0E29E0407341E301BEF0FBC34796C110'
          },
          {
            'meta_universalid': '144BD17E974C2D3F9F5FAC5597606016',
            'companyname': 'QQ-Mail Merge',
            'ups_am_name': '',
            'label': 'QQ-Mail Merge::C',
            'value': '144BD17E974C2D3F9F5FAC5597606016'
          },
          {
            'meta_universalid': '144F5991F01F217A1FF6AC16906145F1',
            'companyname': 'Conference Management Grp',
            'ups_am_name': '',
            'label': 'Conference Management Grp::C',
            'value': '144F5991F01F217A1FF6AC16906145F1'
          },
          {
            'meta_universalid': '17D522FE324C509F4268129EEC376422',
            'companyname': 'Maui Vacations',
            'ups_am_name': '',
            'label': 'Maui Vacations::C',
            'value': '17D522FE324C509F4268129EEC376422'
          },
          {
            'meta_universalid': '1E3ABD313893730EBE022FA2B106461E',
            'companyname': 'API Company',
            'ups_am_name': 'Allen Swope',
            'label': 'API Company::C',
            'value': '1E3ABD313893730EBE022FA2B106461E'
          },
          {
            'meta_universalid': '2126453CE74D7D67389EE78D562000B7',
            'companyname': 'Stapleton Inc.',
            'ups_am_name': 'Chantaye Patton',
            'label': 'Stapleton Inc.::C',
            'value': '2126453CE74D7D67389EE78D562000B7'
          },
          {
            'meta_universalid': '256D336DAAB9F0D7DAE66E6B751783F4',
            'companyname': 'Endress Hauser',
            'ups_am_name': '',
            'label': 'Endress Hauser::C',
            'value': '256D336DAAB9F0D7DAE66E6B751783F4'
          },
          {
            'meta_universalid': '2A3A65F7839CD52239D6696B2B3DF53E',
            'companyname': 'YYYY_Mail Merge Company',
            'ups_am_name': 'Chris Owen',
            'label': 'YYYY_Mail Merge Company::P',
            'value': '2A3A65F7839CD52239D6696B2B3DF53E'
          },
          {
            'meta_universalid': '2CD39213B1400A73B90C70E5D1F39C32',
            'companyname': 'Ezanga',
            'ups_am_name': '',
            'label': 'Ezanga::P',
            'value': '2CD39213B1400A73B90C70E5D1F39C32'
          },
          {
            'meta_universalid': '2D12EE506CE080E280F13F17ACFAC1E4',
            'companyname': 'RUNAMNFL',
            'ups_am_name': 'Marco Wong',
            'label': 'RUNAMNFL::C',
            'value': '2D12EE506CE080E280F13F17ACFAC1E4'
          },
          {
            'meta_universalid': '2E2EF7E71C6C9553289937151A2C64BE',
            'companyname': 'Paydata',
            'ups_am_name': '',
            'label': 'Paydata::C',
            'value': '2E2EF7E71C6C9553289937151A2C64BE'
          },
          {
            'meta_universalid': '3444FBE8ACDAE9E3AED3B893C818BB33',
            'companyname': 'Covington Sales & Service Inc.',
            'ups_am_name': 'Charlie Spaneas',
            'label': 'Covington Sales & Service Inc.::C',
            'value': '3444FBE8ACDAE9E3AED3B893C818BB33'
          },
          {
            'meta_universalid': '3B1E174A9F5CD79B60DFE0F594BC5740',
            'companyname': 'Arcade Rentals',
            'ups_am_name': 'David Adams',
            'label': 'Arcade Rentals::P',
            'value': '3B1E174A9F5CD79B60DFE0F594BC5740'
          },
          {
            'meta_universalid': '3B9F45F635C1991C6165CE4929BEB45A',
            'companyname': 'Voyager Ltd',
            'ups_am_name': '',
            'label': 'Voyager Ltd::C',
            'value': '3B9F45F635C1991C6165CE4929BEB45A'
          },
          {
            'meta_universalid': '40D3ED12812BFFD8DC6930090A103066',
            'companyname': 'ASC Construction Equipment',
            'ups_am_name': 'Mickey Patton',
            'label': 'ASC Construction Equipment::C',
            'value': '40D3ED12812BFFD8DC6930090A103066'
          },
          {
            'meta_universalid': '418BE89FE69DE47CBD741A6E24B2393E',
            'companyname': 'Zz-Merge Company 10-3',
            'ups_am_name': '',
            'label': 'Zz-Merge Company 10-3::C',
            'value': '418BE89FE69DE47CBD741A6E24B2393E'
          },
          {
            'meta_universalid': '4B4C0862E5CA38397A6CB17181140FCA',
            'companyname': 'American Seating',
            'ups_am_name': 'Kevin R Bull',
            'label': 'American Seating::C',
            'value': '4B4C0862E5CA38397A6CB17181140FCA'
          },
          {
            'meta_universalid': '5CAB6401CC92B6A34C985D50C07807C8',
            'companyname': 'Bullman Consulting',
            'ups_am_name': 'Kevin R Bull',
            'label': 'Bullman Consulting::P',
            'value': '5CAB6401CC92B6A34C985D50C07807C8'
          },
          {
            'meta_universalid': '600AB312A7951C2A8A433CD485E19457',
            'companyname': 'Canadian Bearings LLC',
            'ups_am_name': 'Allen Swope',
            'label': 'Canadian Bearings LLC::C',
            'value': '600AB312A7951C2A8A433CD485E19457'
          },
          {
            'meta_universalid': '634762FDBDEC0F19FA5EF9EAF40C8143',
            'companyname': 'Fujitec America',
            'ups_am_name': '',
            'label': 'Fujitec America::C',
            'value': '634762FDBDEC0F19FA5EF9EAF40C8143'
          },
          {
            'meta_universalid': '650D2B827916CE8570FF95F665DA8E98',
            'companyname': 'Mount Pleasant Legal Services',
            'ups_am_name': 'Mickey Patton',
            'label': 'Mount Pleasant Legal Services::C',
            'value': '650D2B827916CE8570FF95F665DA8E98'
          },
          {
            'meta_universalid': '6531CBB3772A17D1F546656A051EFE32',
            'companyname': 'Mcfadden',
            'ups_am_name': '',
            'label': 'Mcfadden::P',
            'value': '6531CBB3772A17D1F546656A051EFE32'
          },
          {
            'meta_universalid': '65CF8DD9B9906B34483E971AD7DF31C3',
            'companyname': 'jacob abc',
            'ups_am_name': '',
            'label': 'jacob abc::C',
            'value': '65CF8DD9B9906B34483E971AD7DF31C3'
          },
          {
            'meta_universalid': '688485E7B0AB0D0AAB668BAB579EF2C6',
            'companyname': 'Gettysburg Address Co.',
            'ups_am_name': 'Charlie Spaneas',
            'label': 'Gettysburg Address Co.::P',
            'value': '688485E7B0AB0D0AAB668BAB579EF2C6'
          },
          {
            'meta_universalid': '699A25672E93D0513AC1FB6CB1EBAE87',
            'companyname': 'JCDECAUX',
            'ups_am_name': '',
            'label': 'JCDECAUX::C',
            'value': '699A25672E93D0513AC1FB6CB1EBAE87'
          },
          {
            'meta_universalid': '6ABE0DEBEC154FC54391D62FBA885065',
            'companyname': 'BBB-Walton Consulting',
            'ups_am_name': 'Chris Owen',
            'label': 'BBB-Walton Consulting::C',
            'value': '6ABE0DEBEC154FC54391D62FBA885065'
          },
          {
            'meta_universalid': '6B20597DD19F5683801D8BA1BE414AA2',
            'companyname': 'Midas International',
            'ups_am_name': '',
            'label': 'Midas International::C',
            'value': '6B20597DD19F5683801D8BA1BE414AA2'
          },
          {
            'meta_universalid': '7453AF0577089861B8486F6F6A601133',
            'companyname': 'Jacobs 160219',
            'ups_am_name': 'c2CRM Administrator',
            'label': 'Jacobs 160219::C',
            'value': '7453AF0577089861B8486F6F6A601133'
          },
          {
            'meta_universalid': '8300ABC63D0996E2BD8FBD2A034CDDE8',
            'companyname': 'Bay Of Pigs, LTD.',
            'ups_am_name': 'Chris Owen',
            'label': 'Bay Of Pigs, LTD.::V',
            'value': '8300ABC63D0996E2BD8FBD2A034CDDE8'
          },
          {
            'meta_universalid': '8901D3B00C4E387818EEF2ED9636D49D',
            'companyname': 'Shafer Equipment Co.',
            'ups_am_name': 'Charlie Spaneas',
            'label': 'Shafer Equipment Co.::C',
            'value': '8901D3B00C4E387818EEF2ED9636D49D'
          },
          {
            'meta_universalid': '8E10973E224DDD9A23696CB2A096C7E0',
            'companyname': 'Low Country Mortgage Corp.',
            'ups_am_name': 'Mickey Patton',
            'label': 'Low Country Mortgage Corp.::C',
            'value': '8E10973E224DDD9A23696CB2A096C7E0'
          },
          {
            'meta_universalid': '91BA200232741A940FD8F323355E4D42',
            'companyname': 'Sloan Valve Company',
            'ups_am_name': 'Charlie Spaneas',
            'label': 'Sloan Valve Company::C',
            'value': '91BA200232741A940FD8F323355E4D42'
          },
          {
            'meta_universalid': '945349F97377A40E29810FEE4B510A9E',
            'companyname': 'Lund International',
            'ups_am_name': '',
            'label': 'Lund International::P',
            'value': '945349F97377A40E29810FEE4B510A9E'
          },
          {
            'meta_universalid': '94F6ED179D2AC0B32C938E0DBC128AC6',
            'companyname': 'Merge test company one',
            'ups_am_name': 'Rick Bensema',
            'label': 'Merge test company one::C',
            'value': '94F6ED179D2AC0B32C938E0DBC128AC6'
          },
          {
            'meta_universalid': '94FC7591C3B99997B59752C1FE6E0120',
            'companyname': 'Frank',
            'ups_am_name': '',
            'label': 'Frank::C',
            'value': '94FC7591C3B99997B59752C1FE6E0120'
          },
          {
            'meta_universalid': '9878C683BC20BD400BDD7C3D5A186FA7',
            'companyname': 'Redwood Accounting Services',
            'ups_am_name': 'Mickey Patton',
            'label': 'Redwood Accounting Services::C',
            'value': '9878C683BC20BD400BDD7C3D5A186FA7'
          },
          {
            'meta_universalid': 'A1D5C83B8DCF017E7B2AC83A790FBE2E',
            'companyname': 'Voyager Ltd',
            'ups_am_name': 'Chris Owen',
            'label': 'Voyager Ltd::C',
            'value': 'A1D5C83B8DCF017E7B2AC83A790FBE2E'
          },
          {
            'meta_universalid': 'A3A97741934D2B20A28531027A65EAC6',
            'companyname': 'Menard Inc',
            'ups_am_name': '',
            'label': 'Menard Inc::C',
            'value': 'A3A97741934D2B20A28531027A65EAC6'
          },
          {
            'meta_universalid': 'A5B00B183470645A740A7CA5CEF2DA4D',
            'companyname': 'API Company',
            'ups_am_name': 'Allen Swope',
            'label': 'API Company::C',
            'value': 'A5B00B183470645A740A7CA5CEF2DA4D'
          },
          {
            'meta_universalid': 'A5B5E77ED227F9B4593D652247846558',
            'companyname': 'Grainger',
            'ups_am_name': '',
            'label': 'Grainger::C',
            'value': 'A5B5E77ED227F9B4593D652247846558'
          },
          {
            'meta_universalid': 'A9971E25931DDD9D4354FC1B9C5508CD',
            'companyname': 'New Deal, Inc.',
            'ups_am_name': 'Chris Owen',
            'label': 'New Deal, Inc.::P',
            'value': 'A9971E25931DDD9D4354FC1B9C5508CD'
          },
          {
            'meta_universalid': 'AB66811A1F18F69F38193DB4816BA35F',
            'companyname': 'API Company',
            'ups_am_name': 'Allen Swope',
            'label': 'API Company::C',
            'value': 'AB66811A1F18F69F38193DB4816BA35F'
          },
          {
            'meta_universalid': 'AB8A57CE19BF25267AF059A021496DA9',
            'companyname': 'Demo Company',
            'ups_am_name': 'Rick Bensema',
            'label': 'Demo Company::C',
            'value': 'AB8A57CE19BF25267AF059A021496DA9'
          },
          {
            'meta_universalid': 'B37F4A915563CEF2194CD506A2A5FED3',
            'companyname': 'Berlin Wall Demolition Co.',
            'ups_am_name': 'Mickey Patton',
            'label': 'Berlin Wall Demolition Co.::C',
            'value': 'B37F4A915563CEF2194CD506A2A5FED3'
          },
          {
            'meta_universalid': 'B380D3A792843FFBB10DB94AFCFB395A',
            'companyname': 'American Seating Company',
            'ups_am_name': 'Allen Swope',
            'label': 'American Seating Company::C',
            'value': 'B380D3A792843FFBB10DB94AFCFB395A'
          },
          {
            'meta_universalid': 'C0B4EE4A57B54CF2EE825551C7F3977E',
            'companyname': 'Guyer Band',
            'ups_am_name': 'Chris Owen',
            'label': 'Guyer Band::V',
            'value': 'C0B4EE4A57B54CF2EE825551C7F3977E'
          },
          {
            'meta_universalid': 'C2363049F60723FDA30D893FA5320E58',
            'companyname': 'Global Enterprises, Inc.',
            'ups_am_name': 'Charlie Spaneas',
            'label': 'Global Enterprises, Inc.::C',
            'value': 'C2363049F60723FDA30D893FA5320E58'
          },
          {
            'meta_universalid': 'C8D5E7F30329B8146DE127FE6813DF18',
            'companyname': 'jason cool',
            'ups_am_name': 'Marco Wong',
            'label': 'jason cool::C',
            'value': 'C8D5E7F30329B8146DE127FE6813DF18'
          },
          {
            'meta_universalid': 'D1592A890538FC6ED9A8905E3E9F1F0F',
            'companyname': 'Social Justice, Inc.',
            'ups_am_name': 'Charlie Spaneas',
            'label': 'Social Justice, Inc.::P',
            'value': 'D1592A890538FC6ED9A8905E3E9F1F0F'
          },
          {
            'meta_universalid': 'DABA52460F611BFC91F77369CC189A96',
            'companyname': 'Hi-Way Equipment Co.',
            'ups_am_name': '',
            'label': 'Hi-Way Equipment Co.::C',
            'value': 'DABA52460F611BFC91F77369CC189A96'
          },
          {
            'meta_universalid': 'DDAF7745A45C6F8860E8AEC1C0EEB19F',
            'companyname': 'Pioneer Metal Finishing',
            'ups_am_name': '',
            'label': 'Pioneer Metal Finishing::C',
            'value': 'DDAF7745A45C6F8860E8AEC1C0EEB19F'
          },
          {
            'meta_universalid': 'DE956A3C4769F2CB893896A80D9A9FEA',
            'companyname': 'Ivy Tech State College',
            'ups_am_name': '',
            'label': 'Ivy Tech State College::C',
            'value': 'DE956A3C4769F2CB893896A80D9A9FEA'
          },
          {
            'meta_universalid': 'DF5521234BA886A70895BB6FBB419B72',
            'companyname': 'TradeCo International',
            'ups_am_name': 'Chantaye Patton',
            'label': 'TradeCo International::C',
            'value': 'DF5521234BA886A70895BB6FBB419B72'
          },
          {
            'meta_universalid': 'DF67F2BBCEFF355DC564295DE532E9A7',
            'companyname': 'General Atomics',
            'ups_am_name': 'Mickey Patton',
            'label': 'General Atomics::P',
            'value': 'DF67F2BBCEFF355DC564295DE532E9A7'
          },
          {
            'meta_universalid': 'E1A4ECDE0112211DD96E4750287846B3',
            'companyname': 'Hammer Equipment Ltd',
            'ups_am_name': '',
            'label': 'Hammer Equipment Ltd::C',
            'value': 'E1A4ECDE0112211DD96E4750287846B3'
          },
          {
            'meta_universalid': 'E8D8468CCCF5056C7975503AC6201199',
            'companyname': 'The Chestand Group',
            'ups_am_name': '',
            'label': 'The Chestand Group::C',
            'value': 'E8D8468CCCF5056C7975503AC6201199'
          },
          {
            'meta_universalid': 'EC93B3A87653A3A0843734095BF87151',
            'companyname': 'American Family Insurance',
            'ups_am_name': 'Chantaye Patton',
            'label': 'American Family Insurance::C',
            'value': 'EC93B3A87653A3A0843734095BF87151'
          },
          {
            'meta_universalid': 'F0947E93D9285129337DB9707D5EFAD0',
            'companyname': 'Clear C2',
            'ups_am_name': 'Chantaye Patton',
            'label': 'Clear C2::C',
            'value': 'F0947E93D9285129337DB9707D5EFAD0'
          },
          {
            'meta_universalid': 'F1FA3FF9D3580B37A818A6138C9940DB',
            'companyname': 'Encephalo Associates',
            'ups_am_name': '',
            'label': 'Encephalo Associates::C',
            'value': 'F1FA3FF9D3580B37A818A6138C9940DB'
          },
          {
            'meta_universalid': 'FA2D8BA758BBE342A1BC0172529D904D',
            'companyname': 'WWW-Target company',
            'ups_am_name': '',
            'label': 'WWW-Target company::C',
            'value': 'FA2D8BA758BBE342A1BC0172529D904D'
          },
          {
            'meta_universalid': 'FB7FCE73583C109C8C9A8062E48378E7',
            'companyname': 'Warwick Communications Inc',
            'ups_am_name': '',
            'label': 'Warwick Communications Inc::C',
            'value': 'FB7FCE73583C109C8C9A8062E48378E7'
          },
          {
            'meta_universalid': 'FE957E4EA2F378E8DE110C5FE8690CAF',
            'companyname': 'Frank01',
            'ups_am_name': 'Jake Allen',
            'label': 'Frank01::C',
            'value': 'FE957E4EA2F378E8DE110C5FE8690CAF'
          },
          {
            'meta_universalid': 'FEAB137F0482AD154BDE321FE822F363',
            'companyname': 'VVVV-Mail Merge Company',
            'ups_am_name': '',
            'label': 'VVVV-Mail Merge Company::C',
            'value': 'FEAB137F0482AD154BDE321FE822F363'
          }
        ]
      })
    }, 2000)
  })
}
