import {initComponentIconLibrary} from '../../src/Icons'

import {
  FaArrowAltCircleLeft as ArrowCircleLeft,
  FaArrowAltCircleRight as ArrowCircleRight,
  FaArrowLeft as ArrowLeft,
  FaArrowRight as ArrowRight,
  FaArrowDown as ArrowDown,
  FaArrowUp as ArrowUp,
  FaAngleLeft as ArrowLeftSmall,
  FaAngleRight as ArrowRightSmall,
  FaAngleUp as ArrowUpSmall,
  FaAngleDown as ArrowDownSmall,
  FaBalanceScale as Balance,
  FaBell as Bell,
  FaBook as Book,
  FaBriefcase as Briefcase,
  FaBuilding as Building,
  FaBullhorn as Bullhorn,
  FaCalendarAlt as Calendar,
  FaCaretDown as CaretDown,
  FaCaretLeft as CaretLeft,
  FaCaretRight as CaretRight,
  FaCaretUp as CaretUp,
  FaShoppingCart as Cart,
  FaChartLine as Chart,
  FaCheck as Check,
  FaCheckSquare as CheckSquare,
  FaRegCheckSquare as CheckSquareOutlined,
  FaChevronLeft as ChevronLeft,
  FaChevronRight as ChevronRight,
  FaChevronDown as ChevronDown,
  FaChevronUp as ChevronUp,
  FaClone as Clone,
  FaTimes as Close,
  FaCode as Code,
  FaCogs as Cogs,
  FaColumns as Columns,
  FaCopy as Copy,
  FaCubes as Cubes,
  FaDatabase as Database,
  FaDollarSign as Dollar,
  FaDownload as Download,
  FaEnvelopeOpen as Email,
  FaEnvelope as Envelope,
  FaFileExcel as Excel,
  FaExternalLinkAlt as ExternalLink,
  FaEye as Eye,
  FaEyeSlash as EyeSlash,
  FaArrowsAltH as FaArrowsH,
  FaFacebook as Facebook,
  FaFeatherAlt as Feather,
  FaList,
  FaMap,
  FaFile as File,
  FaFilter as Filter,
  FaFolder as FolderClosed,
  FaFolderOpen as FolderOpen,
  FaPaperPlane as FormLetter,
  FaGlasses as Glasses,
  FaGlobeAmericas as Globe,
  FaHeart as Heart,
  FaInfo as Help,
  FaHistory as History,
  FaHome as Home,
  FaHourglass as Hourglass,
  FaListAlt as IdCard,
  FaGraduationCap as Knowledgebase,
  FaLifeRing as LifeSaver,
  FaListOl as LineItems,
  FaLinkedin as LinkedIn,
  FaLock as Lock,
  FaSignOutAlt as LogOut,
  FaMinus as Minimize,
  FaExpand as Maximize,
  FaMinusCircle as Minus,
  FaMoneyBill as Money,
  FaBars as Nav,
  FaNewspaper as Newspaper,
  FaPaintBrush as Paint,
  FaPaperclip as Paperclip,
  FaRegPaperPlane as PaperPlane,
  FaPencilAlt as Pencil,
  FaEdit as PencilEdit,
  FaPhone as Phone,
  FaPlusCircle as Plus,
  FaPrint as Print,
  FaRegListAlt as Project,
  FaQuestion as Question,
  FaRegQuestionCircle as QuestionCircle,
  FaCalculator as Quote,
  FaSync as Refresh,
  FaRedo as Repeat,
  FaChartArea as Report,
  FaUserFriends as Roles,
  FaSave as Save,
  FaSearch as Search,
  FaShareAlt as Share,
  FaRssSquare as Social,
  FaTh as Table,
  FaTags as Tags,
  FaCalendarCheck as Task,
  FaAlignJustify as TextFields,
  FaThumbsUp as Thumbs,
  FaTicketAlt as Ticket,
  FaClock as Time,
  FaTrash as Trash,
  FaSitemap as Tree,
  FaTrophy as Trophy,
  FaTruck as Truck,
  FaTwitterSquare as Twitter,
  FaObjectUngroup as Ungroup,
  FaUpload as Upload,
  FaUser as User,
  FaExclamationTriangle as Warning,
  FaWrench as Wrench,
  FaMapPin as MapPin,
  FaUndo as Undo,
  FaFonticonsFi as FontiIcons,
  FaCircle as Circle,
  FaRegCircle as RegCircle,
  FaDotCircle as DotCircle,
  FaCar as Car
} from 'react-icons/fa'

import {
  GoScreenFull as FullScreen,
  GoScreenNormal as NormalScreen
} from 'react-icons/go'

import {
  TiPen as Pen
} from 'react-icons/ti'

import {
  MdCallMerge as Merge,
  MdDragHandle as DragHandle
} from 'react-icons/md'

import {
  GiEarthAmerica as Earth
} from 'react-icons/gi'

import {
  AiOutlineDrag as OutlineDrag
} from 'react-icons/ai'

export {
  Car,
  Merge,
  ArrowCircleLeft,
  ArrowCircleRight,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowLeftSmall,
  ArrowRightSmall,
  ArrowUpSmall,
  ArrowDownSmall,
  Balance,
  Bell,
  Book,
  Briefcase,
  Building,
  Bullhorn,
  Calendar,
  CaretDown,
  CaretLeft,
  CaretRight,
  CaretUp,
  Cart,
  Chart,
  Check,
  CheckSquare,
  CheckSquareOutlined,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  Clone,
  Close,
  Code,
  Cogs,
  Columns,
  Copy,
  Cubes,
  Database,
  Dollar,
  DotCircle,
  Download,
  DragHandle,
  Earth,
  Email,
  Envelope,
  Excel,
  ExternalLink,
  Eye,
  EyeSlash,
  FaArrowsH,
  Facebook,
  FaList,
  FaMap,
  Feather,
  File,
  Filter,
  FolderClosed,
  FolderOpen,
  FormLetter,
  FullScreen,
  Glasses,
  Globe,
  Heart,
  Help,
  History,
  Home,
  Hourglass,
  IdCard,
  Knowledgebase,
  LifeSaver,
  LineItems,
  LinkedIn,
  Lock,
  LogOut,
  MapPin,
  Maximize,
  Minimize,
  Minus,
  Money,
  Nav,
  Newspaper,
  NormalScreen,
  OutlineDrag,
  Paint,
  Paperclip,
  PaperPlane,
  Pen,
  Pencil,
  PencilEdit,
  Phone,
  Plus,
  Print,
  Project,
  Question,
  QuestionCircle,
  Quote,
  Refresh,
  RegCircle,
  Repeat,
  Report,
  Roles,
  Save,
  Search,
  Share,
  Social,
  Table,
  Tags,
  Task,
  TextFields,
  Thumbs,
  Ticket,
  Time,
  Trash,
  Tree,
  Trophy,
  Truck,
  Twitter,
  Undo,
  Ungroup,
  Upload,
  User,
  Warning,
  Wrench,
  FontiIcons
}

initComponentIconLibrary({
  Merge,
  ArrowCircleLeft,
  ArrowCircleRight,
  ArrowLeft,
  ArrowRight,
  ArrowLeftSmall,
  ArrowRightSmall,
  ArrowUpSmall,
  ArrowDownSmall,
  Balance,
  Bell,
  Book,
  Briefcase,
  Building,
  Bullhorn,
  Calendar,
  CaretDown,
  CaretLeft,
  CaretRight,
  CaretUp,
  Cart,
  Chart,
  Check,
  CheckSquare,
  ChevronLeft,
  ChevronRight,
  Clone,
  Close,
  Cogs,
  Columns,
  Copy,
  Cubes,
  Database,
  Dollar,
  Download,
  Email,
  Envelope,
  Excel,
  ExternalLink,
  Eye,
  EyeSlash,
  FaArrowsH,
  Facebook,
  FaList,
  FaMap,
  Feather,
  File,
  Filter,
  FolderClosed,
  FolderOpen,
  FormLetter,
  Glasses,
  Globe,
  Heart,
  Help,
  History,
  Home,
  Hourglass,
  IdCard,
  Knowledgebase,
  LifeSaver,
  LineItems,
  LinkedIn,
  Lock,
  LogOut,
  MapPin,
  Money,
  Nav,
  Newspaper,
  Paint,
  Paperclip,
  PaperPlane,
  Pen,
  Pencil,
  PencilEdit,
  Phone,
  Plus,
  Print,
  Project,
  Question,
  Quote,
  Refresh,
  Repeat,
  Report,
  Roles,
  Save,
  Search,
  Share,
  Social,
  Table,
  Tags,
  Task,
  TextFields,
  Thumbs,
  Ticket,
  Time,
  Trash,
  Tree,
  Trophy,
  Truck,
  Twitter,
  Ungroup,
  Upload,
  User,
  Wrench,
  FontiIcons
})
