import {setPortalNode} from 'c2-dialog'
export reducer from './redux'
export FormDroppable from './FormDroppable'
export {default as FormBuilder, updateFormValues, initCustomFormComponents, initComponentIconLibrary} from './GridFormBuilder'
export {initFormBuilderAjax} from './config'
export {CONDITIONS, TEXT_INPUTS} from './FieldDefinitions/Conditionalinput'
export {default as Typeahead} from './FieldDefinitions/Typeahead'
export {default as Checkbox} from './FieldDefinitions/Checkbox'
export {default as Currency} from './FieldDefinitions/Currency'
export {default as Date} from './FieldDefinitions/Date'
export {default as Datetime} from './FieldDefinitions/Datetime'
export {default as Email} from './FieldDefinitions/Email'
export {default as Input} from './FieldDefinitions/Input'
export {default as Listselect} from './FieldDefinitions/Listselect'
export {default as Multicheckbox} from './FieldDefinitions/Multicheckbox'
export {default as Multiselect} from './FieldDefinitions/Multiselect'
export {default as Number} from './FieldDefinitions/Number'
export {default as Phone} from './FieldDefinitions/Phone'
export {default as Radio} from './FieldDefinitions/Radio'
export {default as Richtextarea} from './FieldDefinitions/Richtextarea'
export {default as Select} from './FieldDefinitions/Select'
export {default as Textarea} from './FieldDefinitions/Textarea'
export {default as Time} from './FieldDefinitions/Time'

setPortalNode(document.getElementById('dialogs'))
