import React, {Component} from 'react'
import PropTypes from 'prop-types'
import Quill from 'quill'
import 'quill/dist/quill.snow.css'

export class ReactQuill extends Component {
  static propTypes = {
    name: PropTypes.string,
    theme: PropTypes.string,
    modules: PropTypes.object,
    formats: PropTypes.array,
    onChange: PropTypes.func,
    value: PropTypes.string,
    readOnly: PropTypes.bool,
    isFocused: PropTypes.bool,
    onFocus: PropTypes.func,
    onBlur: PropTypes.func,
    css: PropTypes.object,
    tabIndex: PropTypes.number,
    className: PropTypes.string
  }

  editor = null

  getEditor = () => this.editor

  createEditor = () => {
    const {theme = 'snow', modules = {}, name} = this.props
    this.editor = new Quill(`#${name}`, {
      theme,
      modules
    })
    this.attachEventListeners()
    this.setReadOnly()
    this.setCurrentValueInEditor()
  }

  attachEventListeners = () => {
    if (!this.editor) return
    this.editor.on('editor-change', this.onEditorChange)
  }

  setReadOnly = () => {
    this.editor.enable(!this.props.readOnly)
  }

  onEditorChange = (event, ...args) => {
    if (event === 'text-change') {
      this.onTextChange(...args)
    }
  }

  debounce = null

  onTextChange = (delta, oldDelta, source) => {
    if (source !== 'api') {
      clearTimeout(this.debounce)
      this.debounce = setTimeout(() => {
        const html = this.editor?.root?.innerHTML || this.editor?.getSemanticHTML() || ''
        this.props.onChange(html)
      }, 750)
    }
  }

  setCurrentValueInEditor = () => {
    const {isFocused} = this.props
    let {value} = this.props
    if (!this.editor || typeof value === 'undefined') return
    let cursor = 0
    if (isFocused) {
      cursor = this.editor.getSelection(true) ? this.editor.getSelection(true).index : 0
    }
    if (typeof value === 'string') {
      value = value.replaceAll(' <', '&nbsp;<')
      value = value.replaceAll('  ', '&nbsp;&nbsp;') // this fixes an issue where multiple spaces/trailing spaces in the markup are truncated - JRA 01/16/25
      if (value.indexOf('<html') > -1) { // this markup was generated by something else, Quill does not include the html tag - JRA 01/31/25
        value = value.replaceAll('<html', '<div') // replace this reference so the user can use normal tables - JRA 01/31/25
        value = value.replaceAll('</html', '</div') // replace this reference so the user can use normal tables - JRA 01/31/25
        value = value.replaceAll('<table', '<div')
        value = value.replaceAll('</table', '</div')
        value = value.replaceAll('<tbody', '<div style="display: flex; flex-direction: column;"')
        value = value.replaceAll('</tbody', '</div')
        value = value.replaceAll('<tr', '<div style="display: flex; flex-direction: row;"')
        value = value.replaceAll('</tr', '</div')
        value = value.replaceAll('<td', '<div style="display: flex; flex-direction: column;"')
        value = value.replaceAll('</td', '</div')
      }
    }
    this.editor.clipboard.dangerouslyPasteHTML(value)
    if (isFocused) {
      this.editor.setSelection(cursor)
    } else {
      this.editor.blur()
    }
  }

  componentDidUpdate (p) {
    if (this.props.value !== p.value) {
      this.setCurrentValueInEditor()
    }
    if (this.props.readOnly !== p.readOnly) {
      this.setReadOnly()
    }
  }

  componentDidMount () {
    this.setCurrentValueInEditor()
    this.createEditor()
  }

  render () {
    const {name, onFocus, onBlur, css = {}, tabIndex, className} = this.props
    return (
      <div
        id={name}
        className={className}
        style={{width: '100%', ...css}}
        onFocus={onFocus}
        onBlur={onBlur}
        tabIndex={tabIndex}
      />
    )
  }
}

export default ReactQuill
